name: lms_unindra
description: A Flutter application for LMS UNINDRA
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.4.0
  html: ^0.15.4
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  path_provider: ^2.1.2
  open_filex: ^4.3.4
  url_launcher: ^6.1.14
  permission_handler: ^11.3.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon_splash.png
  android: true
  ios: false
  fullscreen: true
  android_gravity: center
  image_dark: assets/icon_splash.png
  color_dark: "#FFFFFF"
  android_12:
    image: assets/icon_splash.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image_dark: assets/icon_splash.png
    color_dark: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icon_splash.png
